// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDieRPSt97RTZJ9bw6VYYb_AYB_uwzYQ44',
    appId: '1:921169842014:web:cb31572e1a6f62593a09cf',
    messagingSenderId: '921169842014',
    projectId: 'fire-ui-app',
    authDomain: 'fire-ui-app.firebaseapp.com',
    storageBucket: 'fire-ui-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtBE8Wou6V9Cbqd_x-bPNUcFEwb8WNowE',
    appId: '1:921169842014:android:523a58fcc139a09c3a09cf',
    messagingSenderId: '921169842014',
    projectId: 'fire-ui-app',
    storageBucket: 'fire-ui-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIK2rToE5vuZFQxU4Y1cEP_60vKtfrSeE',
    appId: '1:921169842014:ios:60e887433bf2f52d3a09cf',
    messagingSenderId: '921169842014',
    projectId: 'fire-ui-app',
    storageBucket: 'fire-ui-app.appspot.com',
    iosClientId: '921169842014-b6j085hcljlcvkf2uoqo648hbe7ukebf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireUiApp',
  );
}
